server:
    port: 0

eureka:
    client:
        service-url:
                defaultZone: http://service-registry.one.mls:9821/eureka,
                             http://service-registry.two.mls:9822/eureka

