server:
    port: 0

eureka:
    client:
        service-url:
                defaultZone: http://service-registry.one:9821/eureka,
                             http://service-registry.two:9822/eureka

