server:
    port: 0

eureka:
    client:
        service-url:
                defaultZone: http://eureka-one:9101/eureka/,
                             http://eureka-two:9102/eureka/

property:
    name: local
