spring:    
    application:
        name: circuit-breaker-samples-service


server:
    port: 9111

#feign.client.config.default.connectTimeout=160000000
#feign.client.config.default.readTimeout=160000000
feign:
    circuitbreaker:
        enabled: true
#feign.hystrix.enabled=true
#debug = true
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
    endpoint:
        configprops:
            enabled: true
        info:
            enabled: true
hystrix:
    dashboard:
        proxyStreamAllowList:=*
#management.endpoints.web.base-path=/
