spring:
    application:
        name: service-registry-one


server:
    port: 9821

eureka:
    instance:
        hostname: service-registry.one
    client:
        service-url:
            defaultZone: http://service-registry.two:9822/eureka
            
    renewalPercentThreshold: 0.85
