spring:
    application:
        name: service-registry-one


server:
    port: 9821

eureka:
    instance:
        hostname: service-registry.one.mls        
    client:
        service-url:
            defaultZone: http://service-registry.two.mls:9822/eureka

