spring:
    application:
        name: service-registry-two

server:
    port: 9822


eureka:
    instance:
        hostname: service-registry.two
        
    client:
        service-url:
            defaultZone: http://service-registry.one:9821/eureka
            
    renewalPercentThreshold: 0.85
