spring:
    application:
        name: service-registry-two

server:
    port: 9822


eureka:
    instance:
        hostname: localhost
        
    client:
        service-url:
            defaultZone: http://localhost:9821/eureka
