spring:
    application:
        name: service-registry-one


server:
    port: 9821

eureka:
    instance:
        hostname: localhost        
    client:
        service-url:
            defaultZone: http://localhost:9822/eureka

