spring:
    application:
        name: service-registry-two

server:
    port: 9822


eureka:
    instance:
        hostname: service-registry.two.mls
        
    client:
        service-url:
            defaultZone: http://service-registry.one.mls:9821/eureka
